name: CI Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Etapa de build
        run: echo "Compilando o projeto..."

      - name: Etapa de testes
        run: |
          echo "Executando testes..."
          # simulação de falha (pode trocar pra 0 pra passar)
          exit 1

      - name: Relatório final
        if: ${{ success() }}
        run: echo "✅ Build successful!"
        
      - name: Relatório de falha
        if: ${{ failure() }}
        run: echo "❌ Test failed!"
